// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT IT DIRECTLY.
// Last updated: 2022-06-13T15:11:56.550Z

export enum Quality {
  BLU_RAY = "BluRay",
  CAM = "CAM",
  DVD_R = "DVD-R",
  DVD_RIP = "DVDRip",
  HDDVD = "HDDVD",
  HDTV = "HDTV",
  LASER_RIP = "LaserRip",
  MICRO_HD = "MicroHD",
  R5 = "R5",
  SCREENER = "SCREENER",
  SDTV = "SDTV",
  TELECINE = "TELECINE",
  TELESYNC = "TELESYNC",
  UNKNOWN_RIP = "UnknownRip",
  VCD = "VCD",
  VHS = "VHS",
  WEB_DL = "WEB-DL",
  WORK_PRINT = "WorkPrint",
}

export const QUALITIES = [
  {
    name: Quality.BLU_RAY,
    pattern: /(?<!^)(?:\.|\[| |^)(Blu.?Ray|BDRip|BRip|BR.?Rip|BDMV|BD|BDR|BD25|BD50|BD5|BD9|3D.?BluRay|3DBD|BDRemux|BDRX)(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.CAM,
    pattern: /(?<!^)(?:\.|\[| |^)(CAM|CAMRip|CAM.?Rip)(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.DVD_R,
    pattern: /(?<!^)(?:\.|\[| |^)(DVD.?R|DVD.?Full|Full.?Rip|DVD|DVD.?[59])(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.DVD_RIP,
    pattern: /(?<!^)(?:\.|\[| |^)(DVD.?Rip|DVD.?Mux)(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.HDDVD,
    pattern: /(?<!^)(?:\.|\[| |^)(HDDVD)(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.HDTV,
    pattern: /(?<!^)(?:\.|\[| |^)(HDTV|DVB|DVBRip|DTVRip|HDTVRip)(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.LASER_RIP,
    pattern: /(?<!^)(?:\.|\[| |^)(LaserRip|Laserdisc)(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.MICRO_HD,
    pattern: /(?<!^)(?:\.|\[| |^)(Micro.?HD)(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.R5,
    pattern: /(?<!^)(?:\.|\[| |^)(R5|R5.?LINE)(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.SCREENER,
    pattern: /(?<!^)(?:\.|\[| |^)(SCREENER|SCR|DVDSCR|DVDSCREENER|BDSCR|BR.?Scr|BR.?Screener)(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.SDTV,
    pattern: /(?<!^)(?:\.|\[| |^)(SDTV|PDTV|DSR|DSRip|SATRip|DTHRip|TVRip)(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.TELECINE,
    pattern: /(?<!^)(?:\.|\[| |^)(TELECINE|TC|HDTC)(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.TELESYNC,
    pattern: /(?<!^)(?:\.|\[| |^)(TELESYNC|TS|HDTS|PDVD|PTVD|PreDVDRip)(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.UNKNOWN_RIP,
    pattern: /(?<!^)(?:\.|\[| |^)(UnknownRip|URip)(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.VCD,
    pattern: /(?<!^)(?:\.|\[| |^)(VCD)(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.VHS,
    pattern: /(?<!^)(?:\.|\[| |^)(VHS|VHSRip)(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.WEB_DL,
    pattern:
      /(?<!^)(?:\.|\[| |^)((?:(?:ABC|ATVP|AMZN|BBC|CBS|CC|CR|CW|DCU|DSNP|DSNY|Disney[+]|DisneyPlus|FBWatch|FREE|FOX|HBO|HMAX|HULU|iP|LIFE|MA|MTV|NBC|NICK|NF|RED|TF1|STZ)[.\-])?(?:WEB.?DL|WEB.?DLRip|WEB.?Cap|WEB.?Rip|HC|HD.?Rip|VODR|VODRip|PPV|PPVRip|www|iTunesHD|ithd|AmazonHD|NetflixHD|NetflixUHD|(?<=\d{3,4}[p].)WEB|WEB(?=.[hx]\d{3})))(?=\.|\]| |$)/gi,
  },
  {
    name: Quality.WORK_PRINT,
    pattern: /(?<!^)(?:\.|\[| |^)(WORKPRINT|WP)(?=\.|\]| |$)/gi,
  },
];
