// THIS FILE IS GENERATED AUTOMATICALLY. DO NOT EDIT.
// Data from https://raw.githubusercontent.com/filebot/data/master/media-sources.txt
// Generated by scripts/import-sources.js
// Last updated Wed Apr 07 2021
export const SOURCES = [
  {
    name: "BluRay",
    regex: /(?<!^)(?:\.|\[| |^)(Blu.?Ray|BDRip|BRip|BR.?Rip|BDMV|BD|BDR|BD25|BD50|BD5|BD9|3D.?BluRay|3DBD)(?=\.|\]| |$)/gi,
  },
  {
    name: "CAM",
    regex: /(?<!^)(?:\.|\[| |^)(CAM|CAMRip|CAM.?Rip)(?=\.|\]| |$)/gi,
  },
  {
    name: "DVD-R",
    regex: /(?<!^)(?:\.|\[| |^)(DVD.?R|DVD.?Full|Full.?Rip|DVD|DVD.?[59])(?=\.|\]| |$)/gi,
  },
  {
    name: "DVDRip",
    regex: /(?<!^)(?:\.|\[| |^)(DVD.?Rip|DVD.?Mux)(?=\.|\]| |$)/gi,
  },
  {
    name: "HDDVD",
    regex: /(?<!^)(?:\.|\[| |^)(HDDVD)(?=\.|\]| |$)/gi,
  },
  {
    name: "HDTV",
    regex: /(?<!^)(?:\.|\[| |^)(HDTV|DVB|DVBRip|DTVRip|HDTVRip)(?=\.|\]| |$)/gi,
  },
  {
    name: "LaserRip",
    regex: /(?<!^)(?:\.|\[| |^)(LaserRip|Laserdisc)(?=\.|\]| |$)/gi,
  },
  {
    name: "MicroHD",
    regex: /(?<!^)(?:\.|\[| |^)(Micro.?HD)(?=\.|\]| |$)/gi,
  },
  {
    name: "R5",
    regex: /(?<!^)(?:\.|\[| |^)(R5|R5.?LINE)(?=\.|\]| |$)/gi,
  },
  {
    name: "SCREENER",
    regex: /(?<!^)(?:\.|\[| |^)(SCREENER|SCR|DVDSCR|DVDSCREENER|BDSCR|BR.?Scr|BR.?Screener)(?=\.|\]| |$)/gi,
  },
  {
    name: "SDTV",
    regex: /(?<!^)(?:\.|\[| |^)(SDTV|PDTV|DSR|DSRip|SATRip|DTHRip|TVRip)(?=\.|\]| |$)/gi,
  },
  {
    name: "TELECINE",
    regex: /(?<!^)(?:\.|\[| |^)(TELECINE|TC|HDTC)(?=\.|\]| |$)/gi,
  },
  {
    name: "TELESYNC",
    regex: /(?<!^)(?:\.|\[| |^)(TELESYNC|TS|HDTS|PDVD|PTVD|PreDVDRip)(?=\.|\]| |$)/gi,
  },
  {
    name: "UnknownRip",
    regex: /(?<!^)(?:\.|\[| |^)(UnknownRip|URip)(?=\.|\]| |$)/gi,
  },
  {
    name: "VCD",
    regex: /(?<!^)(?:\.|\[| |^)(VCD)(?=\.|\]| |$)/gi,
  },
  {
    name: "VHS",
    regex: /(?<!^)(?:\.|\[| |^)(VHS|VHSRip)(?=\.|\]| |$)/gi,
  },
  {
    name: "WEB-DL",
    regex: /(?<!^)(?:\.|\[| |^)((?:(?:ABC|ATVP|AMZN|BBC|CBS|CC|CR|CW|DCU|DSNP|DSNY|Disney[+]|DisneyPlus|FBWatch|FREE|FOX|HBO|HMAX|HULU|iP|LIFE|MTV|NBC|NICK|NF|RED|TF1|STZ)[.-])?(?:WEB.?DL|WEB.?DLRip|WEB.?Cap|WEB.?Rip|HC|HD.?Rip|VODR|VODRip|PPV|PPVRip|www|iTunesHD|ithd|AmazonHD|NetflixHD|NetflixUHD|(?<=\d{3,4}[p].)WEB|WEB(?=.[hx]\d{3})))(?=\.|\]| |$)/gi,
  },
  {
    name: "WorkPrint",
    regex: /(?<!^)(?:\.|\[| |^)(WORKPRINT|WP)(?=\.|\]| |$)/gi,
  },
];
